MnkyShop/Controllers/HoaDonController.cs
namespace MinkyShop.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class HoaDonController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HoaDonController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(int? tinhTrang, string? input, DateTime? startDate, DateTime? endDate, int page = 1, int maxRows = 5)
        {
            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"];
            }

            var hoaDons = _context.HoaDon.OrderByDescending(c => c.NgayTao).ToList();

            // Lọc trạng thái hóa đơn
            if (tinhTrang != null)
            {
                hoaDons = hoaDons.Where(c => c.TinhTrang == tinhTrang).ToList();
            }

            // Lọc theo tên hoặc mã hóa đơn
            if (input != null)
            {
                hoaDons = hoaDons.Where(c => c.Id.ToString() == input || c.TenNguoiNhan.Contains(input, StringComparison.OrdinalIgnoreCase)).ToList();
            }

            // Lọc theo ngày
            if (startDate.HasValue)
            {
                hoaDons = hoaDons.Where(c => c.NgayTao.Date >= startDate.Value.Date).ToList();
            }

            if (endDate.HasValue)
            {
                hoaDons = hoaDons.Where(c => c.NgayTao.Date <= endDate.Value.Date).ToList();
            }

            ViewBag.PageCount = (int)Math.Ceiling(hoaDons.Count() / (decimal)maxRows);
            ViewBag.CurrentPageIndex = page;

            hoaDons = hoaDons.Skip((page - 1) * maxRows).Take(maxRows).ToList();

            return View(hoaDons);
        }

        public IActionResult Detail(int id)
        {
            var result = _context.HoaDon.Include(c => c.HoaDonChiTiets)
                    .ThenInclude(c => c.ChiTietSp)
                        .ThenInclude(c => c.MauSac)
                    .Include(c => c.HoaDonChiTiets)
                        .ThenInclude(c => c.ChiTietSp)
                            .ThenInclude(c => c.SanPham)
                                .ThenInclude(c => c.DongSp)
                                    .ThenInclude(c => c.Nsx)
                     .FirstOrDefault(c => c.Id == id);

            return View(result);
        }

        public IActionResult Create(HoaDon obj)
        {
            if (HttpContext.Session.GetString("cart") != null)
            {
                var cart = SessionHelper.GetObjectFromJson<HoaDon>(HttpContext.Session, "cart");

                foreach (var x in cart.HoaDonChiTiets)
                {
                    x.ChiTietSp = null!;
                }

                cart.TenNguoiNhan = obj.TenNguoiNhan;
                cart.DiaChi = obj.DiaChi;
                cart.Sdt = obj.Sdt;
                cart.NgayTao = DateTime.Now;

                _context.HoaDon.Add(cart);

                var result = _context.SaveChanges();

                TempData["Message"] = result > 0 ? "Thêm hóa đơn thành công" : "Thêm hóa đơn thất bại";

                HttpContext.Session.Remove("cart");
            }

            return RedirectToAction("Index", "BanHang");
        }

        public IActionResult CompleteOrder(int id)
        {
            var hoadon = _context.HoaDon.Find(id);

            if(hoadon != null)
            {
                hoadon.TinhTrang = 1;
            }

            var result = _context.SaveChanges();

            TempData["Message"] = result > 0 ? "Hoàn thành đơn hàng thành công" : "Hoàn thành đơn hàng thất bại";

            return RedirectToAction("Index");
        }
    }
}

MnkyShop/Views/HoaDon/Detail.cshtml
@model HoaDon
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row mt-3">
    <div class="col-lg-12">
        <div class="card">
            @{
                if(Model == null)
                {
                    <div>Hóa Đơn Không Tồn Tại</div>
                }
                else
                {
                    <div class="card-body">
                        <div style="display: flex; justify-content: space-between">
                            <div class="card-title text-uppercase">Chi tiết đơn hàng #@Model.Id</div>
                            <span style="text-transform: uppercase; font-weight: bold">Trạng thái: @(Model.TinhTrang == 0 ? "Chưa Hoàn Thành" : "Đã Hoàn Thành")</span>
                        </div>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Ảnh sản phẩm</th>
                                        <th>Tên sản phẩm</th>
                                        <th>Dòng sản phẩm</th>
                                        <th>Hãng</th>
                                        <th>Màu sắc</th>
                                        <th>Số lượng</th>
                                        <th>Đơn giá</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var x in Model.HoaDonChiTiets)
                                    {
                                        <tr>
                                            <td class="align-middle w-25"><img class="w-50" style="border-radius: 25px" src="@x.ChiTietSp.Anh" /></td>
                                            <td class="align-middle">@x.ChiTietSp.SanPham.Ten</td>
                                            <td class="align-middle">@x.ChiTietSp.SanPham.DongSp.Ten</td>
                                            <td class="align-middle">@x.ChiTietSp.SanPham.DongSp.Nsx.Ten</td>
                                            <td class="align-middle">@x.ChiTietSp.MauSac.Ten</td>
                                            <td class="align-middle">@x.SoLuong</td>
                                            <td class="align-middle">@Helper.FormatVietNamDong(x.DonGia)</td>
                                        </tr>
                                    }
                                    <tr>
                                        <td>Tổng số sản phẩm: @Model.HoaDonChiTiets.Count</td>
                                        <td colspan="6" style="text-align: end">Tổng Tiền : @Helper.FormatVietNamDong(Model.TongTien)</td>
                                    </tr>
                                    <tr class="btn-print">
                                        <td>
                                            <button onclick="window.print()" class="btn btn-primary" style="text-align: end">In Hóa Đơn</button>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>

MnkyShop/Views/HoaDon/Index.cshtml
@model List<HoaDon>
@{
    ViewData["Title"] = "Quản lý hóa đơn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row mt-3">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h5>Quản lý hóa đơn</h5>
                </div>

                @* Lọc *@
                <div class="row mb-3">
                    <div class="col-lg-12">
                        <form class="form-inline" method="get" action="@Url.Action("Index")" id="searchForm">
                            <div class="form-row w-100">
                                <!-- Mã hóa đơn hoặc tên-->
                                <div class="col-md-3 mb-2">
                                    <input type="text" class="form-control w-100" name="input" placeholder="Nhập mã hóa đơn hoặc tên khách hàng" value="@ViewContext.HttpContext.Request.Query["input"]">
                                </div>

                                <!-- Ngày bắt đầu và kết thúc -->
                                <div class="col-md-3 mb-2">
                                    <input type="date" class="form-control w-100" name="startDate" value="@ViewContext.HttpContext.Request.Query["startDate"]">
                                </div>

                                <div class="col-md-3 mb-2">
                                    <input type="date" class="form-control w-100" name="endDate" value="@ViewContext.HttpContext.Request.Query["endDate"]">
                                </div>

                                <!-- Trạng thái hóa đơn -->
                                <div class="col-md-2 mb-2">
                                    <select class="form-control w-100" name="tinhTrang">
                                        <option value="">Tất cả trạng thái</option>
                                        <!option value="1" @(ViewContext.HttpContext.Request.Query["tinhTrang"] == "1" ? "selected" : "")>Hoàn thành</!option>
                                        <!option value="0" @(ViewContext.HttpContext.Request.Query["tinhTrang"] == "0" ? "selected" : "")>Chưa hoàn thành</!option>
                                    </select>
                                </div>

                                <!-- Nút tìm kiếm -->
                                <div class="col-md-1 mb-2">
                                    <button type="submit" class="btn btn-primary w-100">Tìm kiếm</button>
                                </div>

                                <!-- Clear bỏ query -->
                                <div class="col-md-1 mb-2">
                                    <a href="@Url.Action("Index")" class="btn btn-danger w-100">Clear</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table" id="myTable">
                        <thead>
                        <tr>
                            <th>Mã hóa đơn</th>
                            <th>Tên người nhận</th>
                            <th>Địa chỉ</th>
                            <th>Tổng tiền</th>
                            <th>Trạng thái</th>
                            <th>Ngày tạo</th>
                            <th>Thao tác</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var x in Model)
                        {
                            <tr>
                                <td>@x.Id</td>
                                <td>@x.TenNguoiNhan</td>
                                <td>@x.DiaChi</td>
                                <td>@Helper.FormatVietNamDong(x.TongTien)</td>
                                <td>@(x.TinhTrang == 0 ? "Chưa hoàn thành" : "Hoàn thành")</td>
                                <td>@x.NgayTao</td>
                                <td>
                                    <a class="btn btn-primary" href="@Url.ActionLink("Detail", "HoaDon", new { x.Id })">Xem chi tiết</a>
                                    @if (x.TinhTrang == 0)
                                    {
                                        <a onclick="return confirm('Bạn có chắc muốn thanh toán?')" class="btn btn-danger" href="@Url.ActionLink("CompleteOrder", "HoaDon", new { x.Id })">Hoàn Thành</a>
                                    }
                                </td>
                            </tr>
                        }
                        </tbody>
                    </table>

                    @* Phân trang *@
                    @await Html.PartialAsync("Pagination", new PaginationViewModel
                    {
                        CurrentPageIndex = ViewBag.CurrentPageIndex,
                        PageCount = ViewBag.PageCount,
                        PageName = "HoaDon"
                    })
                </div>
            </div>
        </div>
    </div>
</div>