MnkyShop/Models/PaginationViewModel.cs
namespace MinkyShop.Models
{
    public class PaginationViewModel
    {
        public int CurrentPageIndex { get; set; }

        public int PageCount { get; set; }

        public string PageName { get; set; } = default!;
    }
}

MnkyShop/Controllers/DongSpController.cs
namespace MinkyShop.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class DongSpController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DongSpController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(int page = 1, int maxRows = 5)
        {
            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"];
            }

            var dongSps = _context.DongSp.ToList();

            ViewBag.PageCount = (int)Math.Ceiling(dongSps.Count() / (decimal)maxRows);
            ViewBag.CurrentPageIndex = page;

            dongSps = dongSps.Skip((page - 1) * maxRows).Take(maxRows).ToList();

            ViewBag.DongSp = dongSps;
            ViewBag.Nsx = _context.Nsx;

            return View();
        }

        public IActionResult Create(DongSp obj)
        {
            _context.DongSp.Add(obj);

            var result = _context.SaveChanges();

            TempData["Message"] = result > 0 ? "Thêm thành công" : "Thêm thất bại";

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Remove(int id)
        {
            var sanPham = _context.DongSp.Find(id);

            if (sanPham == null)
            {
                TempData["Message"] = "Không Tìm Thấy Sản Phẩm";
            }
            else
            {
                _context.DongSp.Remove(sanPham);

                var result = _context.SaveChanges();

                TempData["Message"] = result > 0 ? "Xóa thành công" : "Xóa thất bại";
            }

            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            ViewBag.Nsx = _context.Nsx;

            return View(_context.DongSp.Find(id));
        }

        [HttpPost]
        public IActionResult Update(int id, DongSp obj)
        {
            var sanPham = _context.DongSp.Find(id);

            if (sanPham != null)
            {
                if (sanPham.Id != id)
                {
                    TempData["Message"] = "Dữ Liệu Không Đồng Nhất";
                }
                else
                {
                    sanPham.Ten = obj.Ten;
                    var result = _context.SaveChanges();
                    TempData["Message"] = result > 0 ? "Xóa thành công" : "Xóa thất bại";
                }
            }
            else
            {
                TempData["Message"] = "Không Tìm Thấy Sản Phẩm";
            }

            return RedirectToAction("Index");
        }
    }
}

MnkyShop/Controllers/MauSacController.cs
namespace MinkyShop.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class MauSacController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MauSacController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(int page = 1, int maxRows = 5)
        {
            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"];
            }

            var mauSacs = _context.MauSac.Include(c => c.ChiTietSps).ToList();

            ViewBag.PageCount = (int)Math.Ceiling(mauSacs.Count() / (decimal)maxRows);
            ViewBag.CurrentPageIndex = page;

            mauSacs = mauSacs.Skip((page - 1) * maxRows).Take(maxRows).ToList();

            ViewBag.MauSacs = mauSacs;

            return View();
        }

        public IActionResult Create(MauSac obj)
        {
            _context.MauSac.Add(obj);

            var result = _context.SaveChanges();

            TempData["Message"] = result > 0 ? "Thêm thành công" : "Thêm thất bại";

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Remove(int id)
        {
            var sanPham = _context.MauSac.Find(id);

            if (sanPham == null)
            {
                TempData["Message"] = "Không Tìm Thấy Màu Sắc";
            }
            else
            {
                _context.MauSac.Remove(sanPham);

                var result = _context.SaveChanges();

                TempData["Message"] = result > 0 ? "Xóa thành công" : "Xóa thất bại";
            }

            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            ViewBag.DongSp = _context.DongSp;

            return View(_context.MauSac.Find(id));
        }

        [HttpPost]
        public IActionResult Update(int id, MauSac obj)
        {
            var sanPham = _context.MauSac.Find(id);

            if (sanPham != null)
            {
                if (sanPham.Id != id)
                {
                    TempData["Message"] = "Dữ Liệu Không Đồng Nhất";
                }
                else
                {
                    sanPham.Ten = obj.Ten;
                    var result = _context.SaveChanges();
                    TempData["Message"] = result > 0 ? "Xóa thành công" : "Xóa thất bại";
                }
            }
            else
            {
                TempData["Message"] = "Không Tìm Thấy Màu Sắc";
            }

            return RedirectToAction("Index");
        }
    }
}

MnkyShop/Controllers/NsxController.cs
namespace MinkyShop.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class NsxController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NsxController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(int page = 1, int maxRows = 5)
        {
            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"];
            }

            var nsxs = _context.Nsx.ToList();

            ViewBag.PageCount = (int)Math.Ceiling(nsxs.Count() / (decimal)maxRows);
            ViewBag.CurrentPageIndex = page;

            nsxs = nsxs.Skip((page - 1) * maxRows).Take(maxRows).ToList();

            ViewBag.Nsx = nsxs;
            ViewBag.DongSp = _context.Nsx;

            return View();
        }

        public IActionResult Create(Nsx obj)
        {
            _context.Nsx.Add(obj);

            var result = _context.SaveChanges();

            TempData["Message"] = result > 0 ? "Thêm thành công" : "Thêm thất bại";

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Remove(int id)
        {
            var sanPham = _context.Nsx.Find(id);

            if (sanPham == null)
            {
                TempData["Message"] = "Không Tìm Thấy Sản Phẩm";
            }
            else
            {
                _context.Nsx.Remove(sanPham);

                var result = _context.SaveChanges();

                TempData["Message"] = result > 0 ? "Xóa thành công" : "Xóa thất bại";
            }

            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            ViewBag.DongSp = _context.DongSp;

            return View(_context.Nsx.Find(id));
        }

        [HttpPost]
        public IActionResult Update(int id, Nsx obj)
        {
            var sanPham = _context.Nsx.Find(id);

            if (sanPham != null)
            {
                if (sanPham.Id != id)
                {
                    TempData["Message"] = "Dữ Liệu Không Đồng Nhất";
                }
                else
                {
                    sanPham.Ten = obj.Ten;
                    var result = _context.SaveChanges();
                    TempData["Message"] = result > 0 ? "Sửa thành công" : "Sửa thất bại";
                }
            }
            else
            {
                TempData["Message"] = "Không Tìm Thấy Sản Phẩm";
            }

            return RedirectToAction("Index");
        }
    }
}

MnkyShop/Controllers/SanPhamController.cs
namespace MinkyShop.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class SanPhamController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SanPhamController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(int page = 1, int maxRows = 5)
        {
            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"];
            }

            var sanPhams = _context.SanPham.Include(c => c.ChiTietSps).Include(c => c.DongSp).ThenInclude(c => c.Nsx).ToList();

            ViewBag.PageCount = (int)Math.Ceiling(sanPhams.Count() / (decimal)maxRows);
            ViewBag.CurrentPageIndex = page;

            sanPhams = sanPhams.Skip((page - 1) * maxRows).Take(maxRows).ToList();

            ViewBag.SanPham = sanPhams;
            ViewBag.DongSp = _context.DongSp;

            return View();
        }

        public IActionResult Create(SanPham obj)
        {
            _context.SanPham.Add(obj);

            var result = _context.SaveChanges();

            TempData["Message"] = result > 0 ? "Thêm thành công" : "Thêm thất bại";

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Remove(int id)
        {
            var sanPham = _context.SanPham.Find(id);

            if(sanPham == null)
            {
                TempData["Message"] = "Không Tìm Thấy Sản Phẩm";
            }
            else
            {
                _context.SanPham.Remove(sanPham);

                var result = _context.SaveChanges();

                TempData["Message"] = result > 0 ? "Xóa thành công" : "Xóa thất bại";
            }

            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            ViewBag.DongSp = _context.DongSp;

            return View(_context.SanPham.Find(id));
        }

        [HttpPost]
        public IActionResult Update(int id, SanPham obj)
        {
            var sanPham = _context.SanPham.Find(id);

            if (sanPham != null)
            {
                if(sanPham.Id != id)
                {
                    TempData["Message"] = "Dữ Liệu Không Đồng Nhất";
                }
                else
                {
                    sanPham.Ten = obj.Ten;
                    var result = _context.SaveChanges();
                    TempData["Message"] = result > 0 ? "Xóa thành công" : "Xóa thất bại";
                }
            }
            else
            {
                TempData["Message"] = "Không Tìm Thấy Sản Phẩm";
            }

            return RedirectToAction("Index");
        }
    }
}

MnkyShop/Views/Shared/Pagination.cshtml
@model PaginationViewModel
@if (Model.PageCount > 1)
{
    <div class="store-filter clearfix">
        <!-- Pagination -->
        <ul class="store-pagination">
            @{
                // Gán mặc định CurrentPageIndex = 1 nếu chưa có giá trị hợp lệ
                var currentPageIndex = Model.CurrentPageIndex > 0 ? Model.CurrentPageIndex : 1;
                var pageCount = Model.PageCount > 0 ? Model.PageCount : 1;

                // Lấy query string hiện tại và bỏ tham số "page" nếu có
                var query = ViewContext.HttpContext.Request.QueryString.Value;
                var queryWithoutPage = string.Join("&",
                ViewContext.HttpContext.Request.Query
                .Where(q => !q.Key.Equals("page", StringComparison.OrdinalIgnoreCase))
                .Select(q => $"{q.Key}={q.Value}")
                );
                var baseUrl = $"/{Model.PageName}";
            }

            <!-- Previous page button -->
            <li>
                <a href="@($"{baseUrl}?{queryWithoutPage}&page={(currentPageIndex > 1 ? currentPageIndex - 1 : pageCount)}")">
                    <i class="fa fa-angle-left"></i>
                </a>
            </li>

            <!-- Page number links -->
            @if (pageCount > 1)
            {
                @for (int i = 1; i <= pageCount; i++)
                {
                    <li class=" @(currentPageIndex == i ? "active" : "")">
                        <a href="@($"{baseUrl}?{queryWithoutPage}&page={i}")">@i</a>
                    </li>
                }
            }

            <!-- Next page button -->
            <li>
                <a href="@($"{baseUrl}?{queryWithoutPage}&page={(currentPageIndex < pageCount ? currentPageIndex + 1 : 1)}")">
                    <i class="fa fa-angle-right"></i>
                </a>
            </li>
        </ul>
    </div>
}

MnkyShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Minky Shop</title>
    <!--favicon-->
    <link rel="icon" href="~/assets/images/favicon.ico" type="image/x-icon">
    <!-- Bootstrap core CSS-->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
    <!-- animate CSS-->
    <link href="~/assets/css/animate.css" rel="stylesheet" type="text/css" />
    <!-- Icons CSS-->
    <link href="~/assets/css/icons.css" rel="stylesheet" type="text/css" />
    <!-- Sidebar CSS-->
    <link href="~/assets/css/sidebar-menu.css" rel="stylesheet" />
    <!-- Custom Style-->
    <link href="~/assets/css/app-style.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/assets/css/sell.css" />

    <link rel="stylesheet" href="~/assets/css/toastr.css" />
</head>
<body class="bg-theme bg-theme1">

    <!-- Start wrapper-->
    <div id="wrapper">
        <!--Start sidebar-wrapper-->
        <div id="sidebar-wrapper" data-simplebar="" data-simplebar-auto-hide="true">
            <div class="brand-logo">
                <a href="/banhang">
                    <img src="/assets/images/logo-icon.png" class="logo-icon" alt="logo icon">
                    <h5 class="logo-text">Minky Shop</h5>
                </a>
            </div>
            <ul class="sidebar-menu do-nicescrol">
                <li class="sidebar-header">Thanh điều hướng</li>
                <li>
                    <a href="/banhang">
                        <i class="zmdi zmdi-view-dashboard"></i> <span>Trang chủ</span>
                    </a>
                </li>

                <li class="sidebar-header">Mục Sản Phẩm</li>

                <li>
                    <a href="@Url.Action("Index", "SanPham")">
                        <i class="zmdi zmdi-format-list-bulleted"></i> <span>Sản phẩm</span>
                    </a>
                </li>

                <li>
                    <a href="@Url.Action("Index", "MauSac")">
                        <i class="zmdi zmdi-invert-colors"></i> <span>Màu Sắc</span>
                    </a>
                </li>

                <li>
                    <a href="@Url.Action("Index", "DongSp")">
                        <i class="zmdi zmdi-flattr"></i> <span>Dòng Sản Phẩm</span>
                    </a>
                </li>

                <li>
                    <a href="@Url.Action("Index", "Nsx")">
                        <i class="zmdi zmdi-face"></i> <span>Nhà Sản Xuất</span>
                    </a>
                </li>

                <li class="sidebar-header">Mục Hóa Đơn</li>

                <li>
                    <a href="/hoadon">
                        <i class="zmdi zmdi-grid"></i> <span>Hóa đơn</span>
                    </a>
                </li>
            </ul>

        </div>
        <!--End sidebar-wrapper-->
        <!--Start topbar header-->
        <header class="topbar-nav">
            <nav class="navbar navbar-expand fixed-top">
                <ul class="navbar-nav mr-auto align-items-center">
                    <li class="nav-item">
                        <a class="nav-link toggle-menu" href="#">
                            <i class="icon-menu menu-icon"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <form class="search-bar" action="/banhang/filter">
                            <input type="text" class="form-control" name="name" placeholder="Nhập mã hóa đơn">
                            <a href="#">
                                <i class="icon-magnifier"></i>
                            </a>
                        </form>
                    </li>
                </ul>

                <ul class="navbar-nav align-items-center right-nav-link">
                    <li class="nav-item dropdown-lg">
                        <a class="nav-link" href="@Url.Action("Cart", "BanHang")">
                            <i class="fa fa-shopping-cart"></i>
                        </a>
                    </li>
                    <li class="nav-item dropdown-lg">
                        <a class="nav-link" href="#">
                            <i class="fa fa-bell-o"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        @if (User?.Identity?.IsAuthenticated == true)
                        {
                            <a class="nav-link" href="/Identity/Account/Manage">
                                <span class="user-profile">
                                    <img src="/assets/images/user.png" />
                                </span>
                            </a>
                        }
                        else
                        {
                            <a class="nav-link" href="/Identity/Account/Login">
                                <span class="user-profile">
                                    <img src="/assets/images/user.png" />
                                </span>
                            </a>
                        }
                    </li>
                </ul>
            </nav>
        </header>
        <!--End topbar header-->
        @* <div class="clearfix"></div> *@

        <div class="content-wrapper">
            <div class="container-fluid">
                @RenderBody()
                <!--End Dashboard Content-->
                <!--start overlay-->
                <div class="overlay toggle-menu"></div>
                <!--end overlay-->

            </div>
            <!-- End container-fluid-->

        </div><!--End content-wrapper-->
        <!--Start Back To Top Button-->
        <a href="#" class="back-to-top">
            <i class="fa fa-angle-double-up"></i>
        </a>
        <!--End Back To Top Button-->

    </div><!--End wrapper-->
    <!-- Bootstrap core JavaScript-->
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>


    <!-- sidebar-menu js -->
    <script src="~/assets/js/sidebar-menu.js"></script>

    <!-- Custom scripts -->
    <script src="~/assets/js/app-script.js"></script>

    <!-- Toastr -->
    <script src="~/assets/js/toastr.min.js"></script>

    @if (ViewBag.Message != null)
    {
        <script>
            toastr.success('@ViewBag.Message');
        </script>
    }

    @RenderSection("Scripts", required: false)
</body>
</html>